services:
  postgres:
    image: postgres:16-alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
